// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.haowei.tarsclient.client.testapp;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class TestPrxCallback extends TarsAbstractCallback {

	public abstract void callback_test(String ret);

}
