// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.haowei.tarsclient.client.testapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TestPrx {

	public String test(String name);

	public String test(String name, @TarsContext java.util.Map<String, String> ctx);

	public void async_test(@TarsCallback TestPrxCallback callback, String name);

	public void async_test(@TarsCallback TestPrxCallback callback, String name, @TarsContext java.util.Map<String, String> ctx);
}
